---
title: "Analyze Data from Monte Carlo Simulation"
author: "Chase Latour"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)
library(mcstatsim)
```

# Pull in the Data

```{r}

# CHANGE THE 6 TO 12 WHEN DONE
nscenario <- 12

# Descriptive data from each of the scenarios

for (x in 1:nscenario) {
  # Construct the file name
  file_name <- paste0("describe trial_scenario", x, ".rds")
  
  # Read the RDS file
  dataset <- readRDS(file_name)
  
  # Add the new variable 'scenario'
  dataset$scenario <- x
  
  # Construct the variable name
  var_name <- paste0("describe_scenario", x)
  
  # Assign the dataset to the dynamically named variable
  assign(var_name, dataset)
  
}

combined_describe_trial <- bind_rows(describe_scenario1, describe_scenario2, describe_scenario3,
                                     describe_scenario4, describe_scenario5, describe_scenario6,
                                     describe_scenario7, describe_scenario8, describe_scenario9,
                                     describe_scenario10, describe_scenario11, describe_scenario12)



# Analysis data for each of the scenarios

for (x in 1:nscenario) {
  # Construct the file name
  file_name <- paste0("analyses_scenario", x, ".rds")
  
  # Read the RDS file
  dataset <- readRDS(file_name)
  
  # Add the new variable 'scenario'
  dataset$scenario <- x
  
  # Construct the variable name
  var_name <- paste0("analyses_scenario", x)
  
  # Assign the dataset to the dynamically named variable
  assign(var_name, dataset)
}

combined_analyses <- bind_rows(analyses_scenario1, analyses_scenario2, analyses_scenario3,
                               analyses_scenario4, analyses_scenario5, analyses_scenario6,
                               analyses_scenario7, analyses_scenario8, analyses_scenario9,
                               analyses_scenario10, analyses_scenario11, analyses_scenario12)

```

# Descriptives of Trial Population

```{r}

n_outcomes <- combined_describe_trial %>% 
  group_by(scenario, trt) %>% 
  summarize(n_pregnancies = median(n_people),
            n_censored = median(n_censor),
            n_fetal_deaths = median(n_fd_no_censor),
            n_live_births = median(n_lb_no_censor),
            .groups = 'drop')

totals_by_scenario <- n_outcomes %>% 
  group_by(scenario) %>% 
  summarize(total_pregnancies = sum(n_pregnancies),
            total_censored = sum(n_censored),
            total_fetal_deaths = sum(n_fetal_deaths),
            total_live_births = sum(n_live_births),
            .groups = 'drop')

descriptives <- left_join(n_outcomes, totals_by_scenario, by = ("scenario" = "scenario"))

descriptives2 <- descriptives %>% 
  rowwise() %>% 
  mutate(perc_pregnancies = round(100*n_pregnancies / total_pregnancies, 2),
         perc_censored = round(100*n_censored / total_censored, 2),
         perc_fetal_deaths = round(100*n_fetal_deaths / total_fetal_deaths, 2),
         perc_live_births = round(100*n_live_births / total_live_births, 2)) %>% 
  ungroup() %>% 
  mutate(pregnancies = paste0(n_pregnancies, " (", perc_pregnancies, "%)"),
         censored = paste0(n_censored, " (", perc_censored, "%)"),
         fetal_deaths = paste0(n_fetal_deaths, " (", perc_fetal_deaths, "%)"),
         live_births = paste0(n_live_births, " (", perc_live_births, "%)")) %>% 
  select(scenario, trt, pregnancies, censored, fetal_deaths, live_births) %>% 
  pivot_wider(id_cols = scenario, 
              names_from = trt,
              values_from = c(pregnancies, censored, fetal_deaths, live_births))
# library(openxlsx)
# write.xlsx(descriptives2, file = "descriptive_results.xlsx")
  
descriptives2 %>% 
  knitr::kable(digits = 3, format.args = list(big.mark = ",", scientific = FALSE),
               col.names = c()) %>% # Trying to add commas to larger numbers
  kable_classic() %>% 
  add_header_above(c("Scenario" = 1, "Untreated" = 1, "Treated" = 1, 
                     "Untreated" = 1, "Treated" = 1,
                     "Untreated" = 1, "Treated" = 1, 
                     "Untreated" = 1, "Treated" = 1)) %>% 
  add_header_above(c(" " = 1, "Number of Pregnancies" = 2, 
                     "Number of Censored Pregnancies" = 2,
                     "Number of Fetal Deaths" = 2, 
                     "Number of Live Births" = 2)) 

```

# Results

```{r}

# Create functions to calculate evaluation parameters

## Estimate

calc_estimate <- function(estimates){
  
  est <- mean(estimates)
  est_mcse <- sqrt(var(estimates)/length(estimates))
  return(list(est = est, est_mcse = est_mcse))
  
}

## ESE -- not in mcstatsim package
 
calc_ese <- function(estimates, true_param){
  
  ese <- sqrt(var(estimates))
  ese_mcse <- ese / sqrt(2*(length(estimates)-1))
  return(list(ese = ese, ese_mcse = ese_mcse))
  
}

``` 




```{r}

# Establish the true estimates as the average of the potential outcomes

truth <- combined_analyses %>% 
  group_by(scenario) %>% 
  summarize(composite_truth_r1 = mean(`potential_ risk_composite_trt`),
            composite_truth_r0 = mean(`potential_ risk_composite_untrt`),
            composite_truth_rd = mean(`potential_ rd_composite`),
            composite_truth_rr = exp(mean(log(`potential_ rr_composite`))),
            sga_truth_r1 = mean(`potential_ risk_sga_trt`),
            sga_truth_r0 = mean(`potential_ risk_sga_untrt`),
            sga_truth_rd = mean(`potential_ rd_sga`),
            sga_truth_rr = exp(mean(log(`potential_ rr_sga`))))

combined_analyses2 <- left_join(combined_analyses, truth, by = "scenario")


calculate_simulation_values <- function(dataset, truth_dataset){
  
  hold <- dataset %>% 
    group_by(scenario) %>% 
    summarize(truth_r0 = mean(r0_truth),
              truth_r1 = mean(r1_truth),
              truth_rd = mean(rd_truth),
              truth_rr = mean(rr_truth),
              km_r0 = mean(kmr0),
              # km_r0_se = sqrt((1 / (n()*(n()-1)))*
              #                   sum((kmr0 - km_r0)^2)),
              km_r1 = mean(kmr1),
              # km_r1_se = sqrt((1 / (n()*(n()-1)))*
              #                   sum((kmr1 - km_r1)^2)),
              km_rd = mean(kmrd),
              km_rd_se = sqrt((1 / (n()*(n()-1)))*
                                sum((kmrd - km_rd)^2)),
              km_rd_bias = mean(kmrd - rd_truth),
              km_rd_ese = sqrt((1/(n()-1))*
                                 sum((kmrd - km_rd)^2)),
              km_rd_rmse = sqrt((1/n())*
                                  sum((kmrd - rd_truth)^2)),
              km_rr = mean(kmrr),
              km_lnrr_se = sqrt((1 / (n()*(n()-1)))*
                                  sum((log(kmrr) -
                                         log(km_rr))^2)),
              km_lnrr_bias = mean(log(kmrr) -
                                  log(rr_truth)),
              km_lnrr_ese = sqrt((1/(n()-1))*
                                 sum((log(kmrr) - log(km_rr))^2)),
              km_lnrr_rmse = sqrt((1/n())*
                                  sum((log(kmrr) - log(rr_truth))^2)),
              aj_r0 = mean(ajr0),
              aj_r1 = mean(ajr1),
              aj_rd = mean(ajrd),
              aj_rd_se = sqrt((1 / (n()*(n()-1)))*
                                sum((ajrd -
                                       aj_rd)^2)),
              aj_rd_bias = mean(ajrd - rd_truth),
              aj_rd_ese = sqrt((1/(n()-1))*
                                 sum((ajrd - aj_rd)^2)),
              aj_rd_rmse = sqrt((1/n())*
                                  sum((ajrd - rd_truth)^2)),
              aj_rr = exp(mean(log(ajrr))),
              aj_lnrr_se = sqrt((1 / (n()*(n()-1)))*
                                  sum((log(ajrr) -
                                         log(aj_rr))^2)),
              aj_lnrr_bias = mean(log(ajrr) -
                                  log(rr_truth)),
              aj_lnrr_ese = sqrt((1/(n()-1))*
                                 sum((log(ajrr) - log(aj_rr))^2)),
              aj_lnrr_rmse = sqrt((1/n())*
                                  sum((log(ajrr) - log(rr_truth))^2))
              )
  
  return(hold)
  
}
  

# Get the estimates for the composite outcome

composite_outcome <- combined_analyses2 %>% 
  rename(kmr0 = `km_composite_ r_0`,
         kmr1 = `km_composite_ r_1`,
         kmrd = `km_composite_ rd`,
         kmrr = `km_composite_ rr`,
         ajr0 = `composite_multi_gw r_0`,
         ajr1 = `composite_multi_gw r_1`,
         ajrd = `composite_multi_gw rd`,
         ajrr = `composite_multi_gw rr`,
         r1_truth = composite_truth_r1,
         r0_truth = composite_truth_r0,
         rd_truth = composite_truth_rd,
         rr_truth = composite_truth_rr) %>% 
  calculate_simulation_values() %>% 
  mutate(Outcome = "Composite")
  
# SGA - FD only
sga_fd_only <- combined_analyses2 %>% 
  rename(kmr0 = `km_sga_fd_ r_0`,
         kmr1 = `km_sga_fd_ r_1`,
         kmrd = `km_sga_fd_ rd`,
         kmrr = `km_sga_fd_ rr`,
         ajr0 = `aj_sga_fd_ r_0`,
         ajr1 = `aj_sga_fd_ r_1`,
         ajrd = `aj_sga_fd_ rd`,
         ajrr = `aj_sga_fd_ rr`,
         r1_truth = sga_truth_r1,
         r0_truth = sga_truth_r0,
         rd_truth = sga_truth_rd,
         rr_truth = sga_truth_rr) %>% 
  calculate_simulation_values() %>% 
  mutate(Outcome  = "SGA: 1 Competing Event")

# SGA - All competing events
sga_all <- combined_analyses2 %>% 
  rename(kmr0 = `km_sga_all_ r_0`,
         kmr1 = `km_sga_all_ r_1`,
         kmrd = `km_sga_all_ rd`,
         kmrr = `km_sga_all_ rr`,
         ajr0 = `aj_sga_all_ r_0`,
         ajr1 = `aj_sga_all_ r_1`,
         ajrd = `aj_sga_all_ rd`,
         ajrr = `aj_sga_all_ rr`,
         r1_truth = sga_truth_r1,
         r0_truth = sga_truth_r0,
         rd_truth = sga_truth_rd,
         rr_truth = sga_truth_rr) %>% 
  calculate_simulation_values() %>% 
  mutate(Outcome  = "SGA: 2 Competing Events")

# # Print in Excel file
# analysis <- rbind(composite_outcome, sga_fd_only, sga_all) %>% 
#   select(-c(Outcome, contains("_se"))) %>% 
#   mutate(across(where(is.numeric), ~ round(.x, 2)))
# write.xlsx(analysis, file = "analysis results.xlsx")  

## Then stack and print
rbind(composite_outcome, sga_fd_only, sga_all) %>% 
  select(-c(Outcome, contains("_se"))) %>% 
  mutate(across(where(is.numeric), ~ round(.x, 2))) %>%
  kbl() %>% 
  kable_classic() %>% 
  pack_rows("Composite Outcome", 1, nscenario) %>% 
  pack_rows("SGA with Fetal Death as Only Competing Events", nscenario+1, 2*nscenario) %>% 
  pack_rows("SGA with 2 Competing Events", 2*nscenario+1, 3*nscenario) %>% 
  add_header_above(c(" " = 1, "Risk Estimates" = 2, "Risk Difference" = 1,
                     "Risk Ratio" = 1, "Risk Estimates" = 2, "Risk Difference" = 4, "Risk Ratio" = 4,
                     "Risk Estimates" = 2, "Risk Difference" = 4, "Risk Ratio" = 4)) %>% 
  add_header_above(c(" " =  1, "Truth" = 4, "Kaplan-Meier Estimator" = 10,
                   "Aalen-Johansen Estimator" = 10))
  

```

# Figure: Composite Outcome

```{r}

z <- qnorm(0.975)

figure_data <- rbind(composite_outcome, sga_fd_only, sga_all) %>% 
  select(-starts_with("truth_")) %>% 
  mutate(km_rd_lcl = km_rd - z*km_rd_se,
         km_rd_ucl = km_rd + z*km_rd_se,
         km_rr_lcl = exp(log(km_rr) - z*km_lnrr_se),
         km_rr_ucl = exp(log(km_rr) + z*km_lnrr_se),
         
         aj_rd_lcl = aj_rd - z*aj_rd_se,
         aj_rd_ucl = aj_rd + z*aj_rd_se,
         aj_rr_lcl = exp(log(aj_rr) - z*aj_lnrr_se),
         aj_rr_ucl = exp(log(aj_rr) + z*aj_lnrr_se)
         ) %>% 
  select(-c(contains("_rd_se"), contains("_rd_bias"), contains("rd_ese"), contains("rd_rmse"),
            contains("rr_se"), contains("rr_bias"), contains("rr_ese"), contains("rr_rmse"))) 

figure_efficacy <- figure_data %>% 
  filter(Outcome == "Composite") %>% 
  filter(scenario <= 6) # The first and second 6 scenarios are the exact same for the composite outcome

figure_efficacy2 <- figure_efficacy %>% 
  pivot_longer(cols = -c(scenario, Outcome),
               names_to = "name",
               values_to = "value") %>% 
  mutate(
    Estimator = ifelse(grepl("km", name),
                       "KM",
                       "AJ"),
    parameter = case_when(grepl("_r0", name) ~ "risk_non_initiators",
                          grepl("_r1", name) ~ "risk_initiators",
                          grepl("rd_lcl", name) ~ "RD_LCL",
                          grepl("rd_ucl", name) ~ "RD_UCL",
                          grepl("rd", name) ~ "RD",
                          grepl("rr_lcl", name) ~ "RR_LCL",
                          grepl("rr_ucl", name) ~ "RR_UCL",
                          grepl("rr", name) ~"RR",
    )
  ) %>% 
  pivot_wider(
    id_cols = c(scenario, Outcome, Estimator),
    names_from = parameter,
    values_from = value
  ) %>% 
  left_join(truth, by = "scenario") %>% 
  mutate(rd_absolute_bias = round(abs(composite_truth_rd - RD),4),
         rr_absolute_bias = round(abs(log(composite_truth_rr) - log(RR)), 4)) 

# Create a data frame with unique composite_truth_rd values for each facet
unique_rd_values <- figure_efficacy2 %>% 
  group_by(scenario) %>% 
  summarise(composite_truth_rd = unique(composite_truth_rd),
            composite_truth_r0 = unique(composite_truth_r0),
            composite_truth_r1 = unique(composite_truth_r1))

unique_rr_values <- figure_efficacy2 %>% 
  group_by(scenario) %>% 
  summarise(composite_truth_rr = unique(composite_truth_rr))


#####
## Print out the risks

pdf("Primary efficacy outcome - risks.pdf", height = 6, width = 4.25)

ggplot(figure_efficacy2) +
  # Incidence bars for Drug A and Comparator
  geom_bar(aes(y = Estimator, x = risk_initiators, fill = "Initiators"), stat = "identity", 
           position = position_nudge(y = 0.2), width = 0.4, alpha = 0.7) +
  geom_bar(aes(y = Estimator, x = risk_non_initiators, fill = "Non-Initiators"), stat = "identity", 
           position = position_nudge(y = -0.2), width = 0.4, alpha = 0.4) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
    geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_r0), # + 0.35
             linetype = "dashed", color = "#00BFC4") +
  geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_r1), #  + 0.35
             linetype = "dashed", color = "#F8766D") +
  labs(y = "Scenario", 
       x = "Absolute Risk",
       fill = "Treatment Group", 
       ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        # axis.title.x.top = element_text(hjust = 0.97),
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =10)
        ) +
  theme(strip.placement = "outside") 

dev.off()


pdf("Primary efficacy outcome - RDs.pdf", height = 6, width = 3)

ggplot(figure_efficacy2) +
  geom_point(aes(y = Estimator, x = RD)) +
  geom_label(aes(y = Estimator, x = 0.125, label = scales::number(rd_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_rd), linetype = "dashed", color = "red") +
   geom_label(aes(y = Estimator, x = 0.125, label = scales::number(rd_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
  labs(y = "Scenario", 
       x = "Risk Difference",
       fill = "Treatment Group", 
       ) +
  scale_x_continuous(limits = c(-0.1, 0.15),
                     breaks = seq(-0.1, 0.1, by  = 0.1)) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =10),
        axis.title.x.bottom = element_text(hjust = 0.4)
        ) +
  theme(strip.placement = "outside") 

dev.off()



pdf("Primary efficacy outcome - RRs.pdf", height = 6, width = 3)

ggplot(figure_efficacy2) +
  geom_point(aes(y = Estimator, x = RR)) +
  geom_label(aes(y = Estimator, x = 1.25, label = scales::number(rr_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  geom_vline(data = unique_rr_values, aes(xintercept = composite_truth_rr), linetype = "dashed", color = "red") +
   geom_label(aes(y = Estimator, x = 1.25, label = scales::number(rr_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
  labs(y = "Scenario", 
       x = "Risk Ratio",
       fill = "Treatment Group", 
       ) +
  scale_x_continuous(
    trans='log10',
    limits = c(0.8, 1.3),
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::label_number(accuracy = 0.01)
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =12),
        axis.title.x.bottom = element_text(hjust = 0.4)
        ) +
  theme(strip.placement = "outside") 

dev.off()







# pdf("Primary efficacy outcome.pdf", height = 4, width = 7)
# 
# # Create the plot
# ggplot(figure_efficacy2) +
#   # Incidence bars for Drug A and Comparator
#   geom_bar(aes(y = Estimator, x = risk_initiators, fill = "Initiators"), stat = "identity", 
#            position = position_nudge(y = 0.2, x = -0.1), width = 0.4, alpha = 0.7) +
#   geom_bar(aes(y = Estimator, x = risk_non_initiators, fill = "Non-Initiators"), stat = "identity", 
#            position = position_nudge(y = -0.2, x = -0.1), width = 0.4, alpha = 0.4) +
#   # geom_bar(aes(y = Estimator, x = risk_initiators, fill = "Initiators"), stat = "identity", 
#   #          position = position_nudge(y = 0.2, x = 0.35), width = 0.4, alpha = 0.7) +
#   # geom_bar(aes(y = Estimator, x = risk_non_initiators, fill = "Non-Initiators"), stat = "identity", 
#   #          position = position_nudge(y = -0.2, x = 0.35), width = 0.4, alpha = 0.4) +
#   # Points and error bars for Risk Difference
#   geom_point(aes(y = Estimator, x = RD), 
#              #position = position_dodge(width = 0.8),
#              position = position_nudge(x = 0.65)
#              ) +
#   #geom_text(aes(y = Analysis, x = 0.275, label = absolute_bias), hjust = 1) +
#   geom_label(aes(y = Estimator, x = 0.85, label = scales::number(rd_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
#   geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_rd + 0.65), linetype = "dashed", color = "red") +
#   geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_r0-0.1), # + 0.35
#              linetype = "dashed", color = "#00BFC4") +
#   geom_vline(data = unique_rd_values, aes(xintercept = composite_truth_r1-0.1), #  + 0.35
#              linetype = "dashed", color = "#F8766D") +
#   facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
#   scale_x_continuous(
#     name = "                          Risk (%)",
#     limits = c(-0.1, 0.9),
#     breaks = seq(-0.1, 0.9, by = 0.1),
#     labels = c("0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "", "", "","", ""),
#     sec.axis = sec_axis(~ ., name = "Risk Difference     Absolute Bias",
#                         breaks = seq(0.55, 0.75, by = 0.1),
#                         labels = c(-0.1, 0, 0.1))
#   )  +
#   #geom_vline(xintercept = 0.15, col = "black") +
#   geom_vline(xintercept = -0.1, col = "black") +
#   geom_vline(xintercept = 0.5, col = "black") +
#   geom_vline(xintercept = 0.65, col = "black", linetype = 'dotted') +
#   labs(y = NULL, 
#        x = NULL,
#        fill = "Treatment Group", 
#        ) +
#   theme_minimal() +
#   theme(legend.position = "bottom",
#         axis.title.x.top = element_text(hjust = 0.97),
#         axis.text.y = element_text(size = 12),
#         strip.text = element_text(size = 12),
#         legend.text = element_text(size =12),
#         axis.title.x.bottom = element_text(hjust = 0.09)) +
#   theme(strip.placement = "outside") 
# 
# dev.off()

```

# Figure: SGA Outcome

```{r}


z <- qnorm(0.975)


## Now, we only want 1 set of KM estimates for each scenario and then each of teh AJ estimates. 
## Split this up

km_safety <- figure_data %>% 
  filter(Outcome != "Composite") %>%  
  # filter(scenario <= 3) %>% 
  select(scenario, contains("km")) %>% 
  unique() %>% 
  mutate(Estimator = "KM") %>% 
  rename(risk_non_initiators = km_r0,
         risk_initiators = km_r1,
         RD = km_rd,
         RR = km_rr,
         RD_LCL = km_rd_lcl,
         RD_UCL = km_rd_ucl,
         RR_LCL = km_rr_lcl,
         RR_UCL = km_rr_ucl)

aj_safety <- figure_data %>% 
  filter(Outcome != "Composite") %>% 
  # filter(scenario <= 3) %>% 
  select(scenario, Outcome, contains("aj")) %>% 
  mutate(Estimator = ifelse(grepl("1", Outcome),
                            "AJ: 1 Competing Event",
                            "AJ: 2 Competing Events")) %>% 
  select(-Outcome) %>% 
  rename(risk_non_initiators = aj_r0,
         risk_initiators = aj_r1,
         RD = aj_rd,
         RR = aj_rr,
         RD_LCL = aj_rd_lcl,
         RD_UCL = aj_rd_ucl,
         RR_LCL = aj_rr_lcl,
         RR_UCL = aj_rr_ucl)

figure_safety <- bind_rows(km_safety, aj_safety) %>% 
  left_join(truth, by = "scenario") %>% 
  mutate(rd_absolute_bias = round(abs(sga_truth_rd - RD),4),
         rr_absolute_bias = round(abs(log(composite_truth_rr) - log(RR)), 4)) %>% 
  mutate(Estimator = factor(Estimator,
                            levels = c("AJ: 2 Competing Events",
                                       "AJ: 1 Competing Event",
                                       "KM")))

# Create a data frame with unique composite_truth_rd values for each facet
unique_rd_values <- figure_safety %>% 
  group_by(scenario) %>% 
  summarise(sga_truth_rd = unique(sga_truth_rd),
            sga_truth_r0 = unique(sga_truth_r0),
            sga_truth_r1 = unique(sga_truth_r1),
            sga_truth_rr = unique(sga_truth_rr))




#####
## Print out the risks

pdf("Primary safety outcome - risks.pdf", height = 9, width = 6)

ggplot(figure_safety) +
  # Incidence bars for Drug A and Comparator
  geom_bar(aes(y = Estimator, x = risk_initiators, fill = "Initiators"), stat = "identity", 
           position = position_nudge(y = 0.2), width = 0.4, alpha = 0.7) +
  geom_bar(aes(y = Estimator, x = risk_non_initiators, fill = "Non-Initiators"), stat = "identity", 
           position = position_nudge(y = -0.2), width = 0.4, alpha = 0.4) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
    geom_vline(data = unique_rd_values, aes(xintercept = sga_truth_r0), # + 0.35
             linetype = "dashed", color = "#00BFC4") +
  geom_vline(data = unique_rd_values, aes(xintercept = sga_truth_r1), #  + 0.35
             linetype = "dashed", color = "#F8766D") +
  labs(y = "Scenario", 
       x = "Absolute Risk",
       fill = "Treatment Group", 
       ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        # axis.title.x.top = element_text(hjust = 0.97),
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =10)
        ) +
  theme(strip.placement = "outside") 

dev.off()

figure_safety2 <- figure_safety %>% 
  mutate(
    Estimator = case_when(Estimator == "KM" ~ "KM",
                          Estimator == "AJ: 1 Competing Event" ~ "AJ: 1",
                          Estimator == "AJ: 2 Competing Events" ~ "AJ: 2"),
    Estimator = factor(Estimator, 
                       levels = c("AJ: 2",
                                  "AJ: 1",
                                  "KM"))
  )


pdf("Primary safety outcome - RDs.pdf", height = 9, width = 3)

ggplot(figure_safety2) +
  geom_point(aes(y = Estimator, x = RD)) +
  geom_label(aes(y = Estimator, x = 0.125, 
                 label = scales::number(rd_absolute_bias, accuracy = 0.0001)), 
             fill = "white", label.size = NA) +
  geom_vline(data = unique_rd_values, aes(xintercept = sga_truth_rd), 
             linetype = "dashed", 
             color = "red") +
   geom_label(aes(y = Estimator, x = 0.125, 
                  label = scales::number(rd_absolute_bias, accuracy = 0.0001)), 
              fill = "white", 
              label.size = NA) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
  labs(y = "Scenario", 
       x = "Risk Difference",
       fill = "Treatment Group", 
       ) +
  scale_x_continuous(limits = c(-0.1, 0.15),
                     breaks = seq(-0.1, 0.1, by  = 0.1)) +
  # scale_y_discrete(labels = rep("", 36)) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =10),
        axis.title.x.bottom = element_text(hjust = 0.4),
        axis.title.y=element_blank()
        ) +
  theme(strip.placement = "outside") 

dev.off()



pdf("Primary safety outcome - RRs.pdf", height = 9, width = 3)

ggplot(figure_safety2) +
  geom_point(aes(y = Estimator, x = RR)) +
  geom_label(aes(y = Estimator, x = 1.23, label = scales::number(rr_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  geom_vline(data = unique_rd_values, aes(xintercept = sga_truth_rr), linetype = "dashed", color = "red") +
   geom_label(aes(y = Estimator, x = 1.23, label = scales::number(rr_absolute_bias, accuracy = 0.0001)), fill = "white", label.size = NA) +
  facet_wrap(scenario ~ ., ncol = 1, strip.position = "left") +
  labs(y = "Scenario", 
       x = "Risk Ratio",
       fill = "Treatment Group", 
       ) +
  scale_x_continuous(
    trans='log10',
    limits = c(0.7, 1.3),
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::label_number(accuracy = 0.01)
  ) +
  theme_minimal() +
  theme(legend.position = "bottom",
        axis.text.y = element_text(size = 12),
        strip.text = element_text(size = 12),
        legend.text = element_text(size =12),
        axis.title.x.bottom = element_text(hjust = 0.4),
        axis.title.y=element_blank()
        ) +
  theme(strip.placement = "outside") 

dev.off()

```

# Calculate Stats for Manuscript

## Primary Efficacy Outcome

```{r}


## Efficacy Outcome
composite_outcome %>% 
  select(-c(contains("_se"))) %>% 
  filter(scenario <= 6) %>% 
  mutate(
    km_r0_bias = km_r0 - truth_r0,
    km_r1_bias = km_r1 - truth_r1
  ) %>% 
  ungroup() %>% 
  summarize(
    avg_km0_bias = mean(km_r0_bias),
    avg_km1_bias = mean(km_r1_bias),
    avg_km_rd_bias = mean(abs(km_rd_bias)),
    avg_km_rr_bias = mean(abs(km_lnrr_bias))
  )


  



```

## Primary Safety Outcome - Only Fetal Death as Competing Event

```{r}

sga_fd_only %>% 
  select(-c(contains("_se"))) %>% 
  mutate(
    km_r0_bias = km_r0 - truth_r0,
    km_r1_bias = km_r1 - truth_r1,
    aj_r0_bias = aj_r0 - truth_r0,
    aj_r1_bias = aj_r1 - truth_r1
  ) %>% 
  ungroup() %>% 
  summarize(
    avg_km0_bias = mean(km_r0_bias),
    avg_km1_bias = mean(km_r1_bias),
    avg_km_rd_bias = mean(abs(km_rd_bias)),
    avg_km_rr_bias = mean(abs(km_lnrr_bias)),
    avg_aj0_bias = mean(aj_r0_bias),
    avg_aj1_bias = mean(aj_r1_bias),
    avg_aj_rd_bias = mean(abs(aj_rd_bias)),
    avg_aj_rr_bias = mean(abs(aj_lnrr_bias))
  ) %>% 
  mutate(
    avg_km_bias = (avg_km0_bias + avg_km1_bias) / 2,
    avg_aj_bias = (avg_aj0_bias + avg_aj1_bias) / 2
  )

```

## Primary Safety Outcome - All Competing Events

```{r}

safety_all <- sga_all %>% 
  select(-c(contains("_se")))

```
