---
title: "Multiple outcomes pregnancy"
author: "Chase Latour"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

# Pull in the data generation functions.

```{r}

source("Data generation functions.R")

```


# Upload the parameter Excel file.

```{r}

# Get the directory where the Rmd file is located
rmd_directory <- dirname(rstudioapi::getSourceEditorContext()$path)

# Specify the Excel file name and path relative to the Rmd file location
# excel_file <- file.path(rmd_directory, "Simulation parameters.xlsx")
excel_file <- file.path(rmd_directory, "Scenario 1.xlsx")

# Read SheetA from the Excel file
phase1 <- read_xlsx(excel_file, sheet = "Phase1")
phase2 <- read_xlsx(excel_file, sheet = "Phase2")
phase3 <- read_xlsx(excel_file, sheet = "Phase3")
phase4 <- read_xlsx(excel_file, sheet = "Phase4")
phase5 <- read_xlsx(excel_file, sheet = "Phase5")

```


# Generate the Data

Generate the data for one clinical trial.

```{r}

# Specify the required values for the simulation
n_sim <- 1
settings <- list(
  n = 3000000 # 3 million
)
  

#data <- each_sim(n_sim, n)
for_sim <- c(list(.x = 1:n_sim, .f=each_sim), settings)
# Setting seed once at the beginnign of the simulation, not at
# -- the beginning of each repetition of the DGM, as was done previously.
set.seed(1234)
all_sims <- do.call(purrr::map, args = for_sim)


### Save the file as an RDS file

# Get the directory where the Rmd file is located
rmd_directory <- dirname(rstudioapi::getSourceEditorContext()$path)

# Specify the Excel file name and path relative to the Rmd file location
data_save <- file.path(rmd_directory, "scenario1.rds")

saveRDS(all_sims, file = data_save)

# Eventually - want to write in code that will save these data. 
# -- For other simulations, will want to incorporate parallel processing. This currently takes a while
# -- Maybe should get rid of some of the if/then options if possible.



```
